Python DA Assignment 1: Data Analysis using NumPy and Pandas

In [5]:
import numpy as np
import pandas  as pd

Numpy Arrray Operations

In [6]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [7]:

print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7

In [ ]:
temperatures_f1 = (temperatures_w1 * 9/5) + 32              

print("Temperatures in Fahrenheit:", temperatures_f1)

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [10]:
print("Maximum temperature:", np.max(temperatures_w1))
print("Minimum temperature:", np.min(temperatures_w1))
print("Mean temperature:", round(np.mean(temperatures_w1), 2))

Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.54

In [11]:
print("First three days:", temperatures_w1[:3])    # First three days
print("Weekend temperatures:", temperatures_w1[-2:])   # Weekend (last two days)
print("Middle three days:", temperatures_w1[2:5])      # Middle three days

First three days: [22.5 25.3 20.8]
Weekend temperatures: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

In [12]:

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [ ]:
print("Shape:", temperatures.shape)                # Inspect the 2D array
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total number of elements: 14

In [14]:
print("Week 1 temperatures:", temperatures[0])   #Extract the temperatures for each week and the weekends (last two days)for both weeks.
print("Week 2 temperatures:", temperatures[1])
print("Week 1 weekend:", temperatures[0, -2:]) 
print("Week 2 weekend:", temperatures[1, -2:])

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 weekend: [24.8 21.9]
Week 2 weekend: [22.8 20.1]

Pandas seriess

In [15]:

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [16]:
print("1st rank mark:", marks.iloc[0])    # Access the 1st rank student

print("\nTop 3 ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])     # Retrieve the top 3 ranks 

print("\n3rd rank mark:", marks.iloc[2])   #Retrieve the 3rd rank student

print("\nMarks greater than 90:")     #Filter marks greater than 90 
print(marks[marks > 90])

1st rank mark: 95

Top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd rank mark: 89

Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64

In [17]:
marks.loc['Rank1'] = 100          # Modify the 1st rank student's mark
print("Updated marks:")
print(marks)

marks = marks.drop('Rank5')          # Remove the last rank
print("\nAfter removing Rank5:")
print(marks)

cgpa = marks / 10                    # Calculate CGPA
print("\nCGPA:")
print(cgpa)

Updated marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

Pandas DataFrame

In [18]:

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [23]:
print("Transactions DataFrame:")
display(transactions)

Transactions DataFrame:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [24]:
print("First 5 rows:")
display(transactions.head())

First 5 rows:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [25]:
print("Last 5 rows:")
display(transactions.tail())

Last 5 rows:

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [26]:
print("Shape:", transactions.shape)

Shape: (10, 4)

In [27]:
print("Column names:", transactions.columns)

Column names: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [29]:
print("Data types:")
print(transactions.dtypes)

Data types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [30]:
print("Basic information:")
transactions.info()

Basic information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [31]:
print("Product Category and Amount:")
display(transactions[['ProductCategory', 'Amount']])

Product Category and Amount:

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [32]:
print("Last 3 columns:")
display(transactions.iloc[:, -3:])

Last 3 columns:

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [33]:
print("North region with Amount > 200:")
display(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

North region with Amount > 200:

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [34]:
print("Product Category Counts:")
print(transactions['ProductCategory'].value_counts())

Product Category Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [35]:
print("Unique Regions:")
print(transactions['Region'].unique())

Unique Regions:
['North' 'South' 'East' 'West']

In [36]:
print("Mean Amount by Region:")
print(transactions.groupby('Region')['Amount'].mean())

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [37]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print("After modifying Amount:")
display(transactions)

After modifying Amount:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
transactions['Discount'] = transactions['Amount'] * 0.10
print("After adding Discount:")
display(transactions)

After adding Discount:

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [39]:
transactions = transactions[transactions['TransactionID'] != 109]
print("After removing TransactionID 109:")
display(transactions)

After removing TransactionID 109:

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [40]:
transactions = transactions.drop(columns=['Discount'])
print("After deleting Discount column:")
display(transactions)

After deleting Discount column:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400